### PR TITLE
TextField in CommandBox will remain the same whenever invalid keypress detected

### LINKED ISSUE #311: [PE-D] Command History - Viewing Most Recent Command
Bug: When viewing most recent/oldest command, have to press arrow twice to retrieve the previous/next command.

How to replicate:
1. `edit 1 -n Alex`
2. `delete 1`
3. `filter -sid A1234567X`
4. Press up arrow until `edit 1 -n Alex` is shown
5. Press up arrow once more.
6. Press down arrow once. Command shown is still `edit 1 -n Alex` instead of `delete 1`

This can be replicated for most recent command as well.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: mslevis/ped#1

### LINKED ISSUE #317: [PE-D] Command History - Does not reset when command box is cleared
In CLI, it is expected that most recent command is shown when command box is empty and UP arrow is pressed.

How to replicate:

1. `edit 1 -n Alex`
1. `delete 1`
1. `filter -sid A1234567X`
1. Press up arrow until `delete 1` is shown.
1. Delete the current input field `delete 1` such that command box is empty.
1. Press up arrow once. `edit 1 -n Alex` is shown instead of `filter -sid A1234567X`.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: mslevis/ped#2

### LINKED ISSUE #372: `CommandHistory`: User allowed to access "next command" with down button when typing incorrect input
Should the user not be allowed to press the down key after an incorrect input? Since the incorrect input would be the most recently entered command

https://user-images.githubusercontent.com/40263305/139579240-1f071095-0580-4773-81c7-84e87d83e7fd.mov

### PR DESCRIPTION
**Pull request by shermannws**
(instead of setting the textfield to be of an empty string)

fixes #311 
fixes #372 
fixes #317 

Implemented a new exception called `CommandHistoryException` that will be thrown when an unexpected or invalid keypress is detected.

For testing and review please.

### CODE REVIEW

File: src/main/java/seedu/programmer/ui/CommandBox.java [hunk 1]
```diff
@@ -59,15 +60,21 @@ private void handleCommandEntered() {
...
+            } else if (event.getCode() == KeyCode.DOWN) {
+                commandTextField.setText(commandHistory.getNextCommand());
+            } else {
+                return;
+            }
+            setStyleToDefault();
+            commandTextField.end();
+            event.consume(); // Consume Event
+        } catch (CommandHistoryException e) {
+            commandTextField.end();
```
Comment (AllardQuek) [inline src/main/java/seedu/programmer/ui/CommandBox.java:75]: Not sure if this is the best implementation to solve this from a code quality perspective, because compared to the previous implementation now we can't really tell what went "wrong" if a CommandHistory Exception were to occur. It also seems like we are using the catching of an exception to carry out the expected functionality.

Comment (AllardQuek) [reply src/main/java/seedu/programmer/ui/CommandBox.java:75]: We could add a log here, but my gut feeling is that a new exception here isn't really necessary. Maybe I can try an alternative method and make a PR? I'm thinking it is possible to do this with if-else conditional statements.

Comment (shermannws) [reply src/main/java/seedu/programmer/ui/CommandBox.java:75]: Thanks man! Very true, I am apprehensive of using an exception here as a 'control flow'.
@AllardQuek yes sure, you can pull this branch to your local and give it a try and just push back and it will update in this PR. I will consider what I can possibly do and discuss with you offline to see what could work best. Thanks a lot!

Comment (AllardQuek) [reply src/main/java/seedu/programmer/ui/CommandBox.java:75]: Ok sure! Is it ok if I push to the same branch? I created a branch from this branch to work on just in case. I'll make a separate PR with that first and mention this PR, in case you want to keep a record of your implementation. Thanks :D
