### PR TITLE
Fix Lab Errors

### LINKED ISSUE #314: [PE-D] large lab number produces invalid command format
-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: waynetee/ped#3

### LINKED ISSUE #319: [PE-D] (Corner case) For large total lab score, the <= condition is not enforced correctly
I have set the score of lab 3 to 1x10^47 but am able to set a student's score to 1x10^47 + 5

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: wpinrui/ped#9

### PR DESCRIPTION
**Pull request by reddevil1313**
Fixes #319 
Fixes #314

### CODE REVIEW

**Review by erwinqxy — APPROVED** [review]
LGTM

File: src/main/java/seedu/programmer/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -158,6 +160,8 @@ public static Integer parseTotal(String total) throws ParseException {
                 return 0;
             } else if (res <= 0) {
                 throw new ParseException(Lab.MESSAGE_LAB_TOTAL_SCORE_CONSTRAINT);
+            } else if (res > 100) {
+                throw new ParseException(Lab.MESSAGE_LAB_TOTAL_SCORE_CONSTRAINT);
```
Comment (AllardQuek) [inline src/main/java/seedu/programmer/logic/parser/ParserUtil.java:164]: Similar issue to MESSAGE_LAB_NUMBER_CONSTRAINT

File: src/main/java/seedu/programmer/logic/parser/ParserUtil.java [hunk 2]
```diff
@@ -111,6 +111,8 @@ public static int parseLabNum(String labNum) throws ParseException {
             int value = Integer.parseInt(labNum);
             if (value <= 0) {
                 throw new ParseException(Lab.MESSAGE_LAB_NUMBER_CONSTRAINT);
+            } else if (value > 14) {
+                throw new ParseException(Lab.MESSAGE_LAB_NUMBER_CONSTRAINT);
```
Comment (AllardQuek) [inline src/main/java/seedu/programmer/logic/parser/ParserUtil.java:115]: It seems the same exceptions are thrown in both cases here. Could we combine both conditions with an || operator?
